[project]
name = "qrcode-pixel-font"
version = "0.0.0"
requires-python = ">=3.14"

dependencies = [
    "pixel-font-builder==0.0.47",
    "pixel-font-knife==0.0.20",
    "qrcode==8.2",
    "tqdm==4.67.1",
    "loguru==0.7.3",
    "cyclopts==4.4.4",
]
